[project]
name = "tinydsl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.119.0",
    "matplotlib>=3.10.7",
    "uvicorn>=0.38.0",
]
