name: Test

permissions:
  contents: read

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push' && github.ref != 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.base_ref == 'main')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv venv
          uv sync

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          # Run only unit tests (exclude integration tests that require a running server)
          # This runs 129/148 tests (19 integration tests excluded)
          pytest tests/ -v --tb=short -m "not integration and not requires_server"

      - name: Test summary
        if: always()
        run: |
          # cleanup after tests are done
          echo "✅ Unit tests completed (integration tests skipped)"
          echo "ℹ️  To run all tests including integration: pytest tests/ -v"
          rm -rf output memory
